receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 5s
          static_configs:
            - targets: ["0.0.0.0:8888"]
        - job_name: "api01"
          scrape_interval: 5s
          static_configs:
            - targets: ["host.docker.internal:4000"]
        - job_name: "api02"
          scrape_interval: 5s
          static_configs:
            - targets: ["host.docker.internal:4001"]

processors:
  batch:

extensions:
  headers_setter:
    headers:
      - key: X-Scope-OrgID
        value: demo

exporters:
  prometheusremotewrite:
    endpoint: http://load-balancer:9009/api/v1/push
    auth:
      authenticator: headers_setter

service:
  extensions: [headers_setter]
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite]
